---
efiBootLoader: "grub"
kernel: "vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: "10"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubeProbe: "grub-probe"
efiBootMgr: "efibootmgr"

installEFI: true
installMBR: false
efiBootloaderId: Moobian
grubInstallArgs: [ "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Moobian", "--force" ]
preCommands:
  - "/etc/calamares/scripts/mount-chroot.sh"
  - "/etc/calamares/scripts/mount-esp.sh"
  - "/etc/calamares/scripts/check-blkid.sh"

