---
type: "shellprocess"
chroot: true
timeout: 120
verbosity: 2
script:
    - "apt purge -y calamares"
    - "apt autoremove -y --purge"
    - "apt clean"
    - "gnome-extensions enable dash-to-panel@jderose9.github.com"
    - "gnome-extensions enable ding@rastersoft.com"
    - "gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com"
