---
type: "shellprocess"
chroot: true
timeout: 120
verbosity: 2
script:
    - "apt purge -y calamares"
    - "apt autoremove -y --purge"
    - "apt clean"
    - "sed -i '\\|deb \\[trusted=yes\\] file:/run/live/medium trixie main|d' /etc/apt/sources.list"
    - "echo 'export PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/MoobianScripts\"\n' >> /etc/bash.bashrc"
    - "mkdir -p /etc/sudoers.d"
    - "echo 'Defaults secure_path = \"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/MoobianScripts\"' > /etc/sudoers.d/MoobianScripts"
    - "chmod 0440 /etc/sudoers.d/MoobianScripts"
