---
type: "shellprocess"
chroot: true
timeout: 120
verbosity: 2
script:
    - "apt purge -y calamares"
    - "apt autoremove -y --purge"
    - "apt clean"
    - "sed -i '\\|deb \\[trusted=yes\\] file:/run/live/medium trixie main|d' /etc/apt/sources.list"
