---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
showDonateUrl:          https://kde.org/community/donations/
requirements:
    # Amount of available disk, in GiB. Floating-point is allowed here.
    requiredStorage:    5.5

    # Amount of available RAM, in GiB. Floating-point is allowed here.
    requiredRam:        1.0

    internetCheckUrl:   http://google.com

    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
        - "false"
        - slow-true
        - snark
    required:
        # - storage
        - ram
        # - root

