# Standard begining
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false

# Use modules in the /etc/calamares/modules folder
modules-search: [ local ]

# use branding of choice
branding: default

# Calamares modules to run
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - locale
  - keyboard
  - localecfg
  - fstab
#  - plymouthcfg
  - shellprocess
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - initramfs
  - grubcfg
  - bootloader
  - umount
- show:
  - finished
